[package]
name = "relanote-stdlib"
description = "Standard library for relanote"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
relanote-core.workspace = true
relanote-ast.workspace = true
relanote-eval.workspace = true
