[package]
name = "relanote-lexer"
description = "Lexer/tokenizer for relanote language"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
relanote-core.workspace = true
logos.workspace = true
thiserror.workspace = true
